### ISSUE TITLE
lgpio.error: 'GPIO not allocated'

### ISSUE THREAD

**Issue by akza** [zerowriter/zerowriter1#26]
I am running a Raspberry PI 2W with a 4.2inch Waveshare (Rev2.2)
So far, I have followed all the instructions, and triple checked my pin setup

when trying to execute
`sudo python main.py`

I get the following:

> epd.config loaded new
Traceback (most recent call last):
  File "/home/zero/zerowriter1/e-Paper/RaspberryPi_JetsonNano/python/examples/main.py", line 32, in <module>
    zero_writer.initialize()
  File "/home/zero/zerowriter1/e-Paper/RaspberryPi_JetsonNano/python/examples/zerowriter.py", line 156, in initialize
    self.epd.init()
  File "/home/zero/zerowriter1/e-Paper/RaspberryPi_JetsonNano/python/examples/waveshare_epd/epd4in2_V2.py", line 127, in init
    if epdconfig.module_init() != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/zerowriter1/e-Paper/RaspberryPi_JetsonNano/python/examples/waveshare_epd/epdconfig.py", line 73, in module_init
    self.GPIO.setup(self.CS_PIN, self.GPIO.OUT)
  File "/usr/lib/python3/dist-packages/RPi/GPIO/__init__.py", line 704, in setup
    initial = _check(lgpio.gpio_read(_chip, gpio))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 903, in gpio_read
    return _u2i(_lgpio._gpio_read(handle&0xffff, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 458, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO not allocated'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/zero/zerowriter1/e-Paper/RaspberryPi_JetsonNano/python/examples/main.py", line 40, in <module>
    zero_writer.epd.init()
  File "/home/zero/zerowriter1/e-Paper/RaspberryPi_JetsonNano/python/examples/waveshare_epd/epd4in2_V2.py", line 127, in init
    if epdconfig.module_init() != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/zerowriter1/e-Paper/RaspberryPi_JetsonNano/python/examples/waveshare_epd/epdconfig.py", line 73, in module_init
    self.GPIO.setup(self.CS_PIN, self.GPIO.OUT)
  File "/usr/lib/python3/dist-packages/RPi/GPIO/__init__.py", line 704, in setup
    initial = _check(lgpio.gpio_read(_chip, gpio))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 903, in gpio_read
    return _u2i(_lgpio._gpio_read(handle&0xffff, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 458, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO not allocated'

After trying to find a solution for this I am unable to get past this. It might be a known issue that I cant find documented, so any guidance would be hugely appreciated here!

**Comment by zerowriter** [comment]
Hey - does the demo code from waveshare run?

**Comment by akza** [comment]
Hi!! Thanks for the speedy reply :) 

I do not see any activity on the ePaper at this point.

**Comment by zerowriter** [comment]
I would start by going to the waveshare website and running the demo code
for your display -/ this will verify that your wiring is good.

If the demo runs, then I can help take it from there!

**Comment by zerowriter** [comment]
worth mentioning — using the 2.2 branch? The main branch could throw some
weird errors if you are using a 2.2 display

**Comment by akza** [comment]
Yes, definitely using the 2.2 branch. 
Here is the wiring guide I followed - just to double check that I am connecting things correctly.
<img width="707" alt="image" src="https://github.com/user-attachments/assets/da85a64e-8099-4e0c-9535-5739a0b06c93">

**Comment by zerowriter** [comment]
From my understanding if you can use bookworm 32bit on a 6.1 kernel you’d
avoid it.

https://github.com/raspberrypi/linux/issues/6037

So I would try that as a starting point.

**Comment by zerowriter** [comment]
https://downloads.raspberrypi.com/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2024-10-28/2024-10-22-raspios-bullseye-armhf-lite.img.xz

Try this one. (Raspberry pi legacy os lite runing bullseye)

Or possibly an archived version of bookworm:

https://www.raspberrypi.com/software/operating-systems/


I would think this should resolve.

**Comment by akza** [comment]
Thanks! This is super helpful. Everything I have been digging up seems to indicate some gpio conflicts! Let me give this a go!!! Appreciate it!

**Comment by akza** [comment]
> Or possibly an archived version of bookworm:
https://www.raspberrypi.com/software/operating-systems/

I tried the arched Bookworm release (from March 2024) and this resolved the GPIO issue for me also!

Thank you!!

**Comment by kaisxu** [comment]
I hit similar issue in 6.12 kernel, it turn out that I need to install `rpi.gpio`
```
sudo apt install python3-rpi.gpio
```

**Comment by SiderBright** [comment]
How did you guys add ssh user and wifi to the arched image? Been messing around with google and haven't got it working yet.

**Comment by jam-dad** [comment]
> I hit similar issue in 6.12 kernel, it turn out that I need to install `rpi.gpio`
> 
> ```
> sudo apt install python3-rpi.gpio
> ```

THIS!!
